server:
  port: 8081
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  hibernate:
    ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


