
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  hibernate:
    ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


